//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Nwd.BackOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        [Key]
        [HiddenInput]
        public int AlbumId { get; set; }
        [Required]
        public int Number { get; set; }
        public System.TimeSpan Duration { get; set; }
        [HiddenInput]
        public string FileRelativePath { get; set; }
        [HiddenInput]
        public Nullable<int> Song_Id { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Song Song { get; set; }
    }
}
